version: "3.9"

services:
  db:
    container_name: iballot-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sh:/usr/local/bin/init.sh
      - ./backend/dump.sql:/usr/local/bin/dump.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["sh", "/usr/local/bin/init.sh"]

  backend:
    container_name: iballot-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    ports:
      - "${PORT}:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: npm run server
    environment:
      - CONTRACT_ADDRESS
      - PRIVATE_KEY
      - RELAYER_PRIVATE_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PORT
      - DB_URL
      - SECRET_SALT
      - RPC_URL
      - ADMIN_TOKEN

  frontend:
    container_name: iballot-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - PORT=3000
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_AUTH_DOMAIN=${VITE_AUTH_DOMAIN}
      - VITE_PROJECT_ID=${VITE_PROJECT_ID}
      - VITE_STORAGE_BUCKET=${VITE_STORAGE_BUCKET}
      - VITE_MESSAGING_SENDER_ID=${VITE_MESSAGING_SENDER_ID}
      - VITE_APP_ID=${VITE_APP_ID}

  test:
    container_name: iballot-test
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    command: npx jest
    environment:
      - NODE_ENV=test
      - CONTRACT_ADDRESS
      - PRIVATE_KEY
      - RELAYER_PRIVATE_KEY
      - FIREBASE_AUTH_EMULATOR_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PORT=5050
      - FIREBASE_PROJECT_ID
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PRIVATE_KEY
      - DB_URL
      - SECRET_SALT
      - RPC_URL
      - ADMIN_TOKEN
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  db-seed:
    image: postgres:16-alpine
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/dump.sql:/dump.sql
    entrypoint: >
      sh -c "
        until pg_isready -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do sleep 1; done
        psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /dump.sql
      "

volumes:
  db_data:
  backend_node_modules:
  frontend_node_modules:
